/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bo.IpotecaBO;
import entity.Ipoteca;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Andrei Buculea
 */
public class frameIpoteca extends javax.swing.JFrame {

    /**
     * Creates new form frameIpoteca
     */
    private IpotecaBO ibo = new IpotecaBO();

    public frameIpoteca() {
        initComponents();
        listIpoteca();
        setTitle("Ipoteca");
    }

    public void listIpoteca() {
        ibo.listIpoteca(tbIpoteca);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtSumaRestituit = new javax.swing.JTextField();
        txtNrCont = new javax.swing.JTextField();
        txtCodFiliala = new javax.swing.JTextField();
        txtNrClient = new javax.swing.JTextField();
        txtSumaImprumutata = new javax.swing.JTextField();
        txtTipCont = new javax.swing.JTextField();
        txtTipIpoteca = new javax.swing.JTextField();
        txtRataDobanzii = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbIpoteca = new javax.swing.JTable();
        btnLista = new javax.swing.JButton();
        btnAdaugare = new javax.swing.JButton();
        btnEditare = new javax.swing.JButton();
        btnStergere = new javax.swing.JButton();
        btnResetare = new javax.swing.JButton();
        btnInapoi1 = new javax.swing.JButton();
        btnSumaC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ipoteca");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 1810, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nr. cont");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Codul filialei de conducere");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Suma imprumutata");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Suma de restituit");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Tip cont");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Tip ipoteca");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Rata dobanzii");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Nr. client");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));
        jPanel1.add(txtSumaRestituit, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 320, -1));

        txtNrCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNrContActionPerformed(evt);
            }
        });
        jPanel1.add(txtNrCont, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 400, -1));
        jPanel1.add(txtCodFiliala, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 320, -1));
        jPanel1.add(txtNrClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 320, -1));
        jPanel1.add(txtSumaImprumutata, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 320, 30));
        jPanel1.add(txtTipCont, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 320, -1));
        jPanel1.add(txtTipIpoteca, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 320, -1));
        jPanel1.add(txtRataDobanzii, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 210, -1));

        tbIpoteca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbIpoteca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbIpotecaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbIpoteca);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, 1160, 460));

        btnLista.setText("lista dobanzi");
        btnLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaActionPerformed(evt);
            }
        });
        jPanel1.add(btnLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 190, 60));

        btnAdaugare.setText("Adaugare");
        btnAdaugare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdaugareActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdaugare, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 550, 250, 150));

        btnEditare.setText("Editare");
        btnEditare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditareActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditare, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 550, 250, 150));

        btnStergere.setText("Stergere");
        btnStergere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStergereActionPerformed(evt);
            }
        });
        jPanel1.add(btnStergere, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 550, 250, 150));

        btnResetare.setText("Resetare");
        btnResetare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetareActionPerformed(evt);
            }
        });
        jPanel1.add(btnResetare, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 550, 250, 150));

        btnInapoi1.setText("Inapoi");
        btnInapoi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInapoi1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnInapoi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 550, 250, 150));

        btnSumaC.setText("Suma creditelor");
        btnSumaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaCActionPerformed(evt);
            }
        });
        jPanel1.add(btnSumaC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 190, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1810, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNrContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNrContActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNrContActionPerformed

    private void btnAdaugareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdaugareActionPerformed
        // TODO add your handling code here:
        if (txtNrCont.getText().isEmpty() || txtCodFiliala.getText().isEmpty() || txtSumaImprumutata.getText().isEmpty()
                || txtSumaRestituit.getText().isEmpty() || txtTipCont.getText().isEmpty() || txtRataDobanzii.getText().isEmpty()
                || txtNrClient.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "completati toate campurile!");
        } else {
            Ipoteca ipt = new Ipoteca();
            
            ipt.setNumar_cont(txtNrCont.getText());
            ipt.setCod_filiala_conducere(Integer.parseInt(txtCodFiliala.getText()));
            ipt.setSuma_imprumutata(Float.parseFloat(txtSumaImprumutata.getText()));
            ipt.setSuma_de_restituit(Float.parseFloat(txtSumaRestituit.getText()));
            ipt.setTip_cont(txtTipCont.getText());
            ipt.setTip_ipoteca(txtTipIpoteca.getText());
            ipt.setRata_dobanzii(Float.parseFloat(txtRataDobanzii.getText()));
            ipt.setNr_client(Integer.parseInt(txtNrClient.getText()));
            String mesaj = ibo.addIpoteca(ipt);
            JOptionPane.showMessageDialog(null, mesaj);
            clean_field();
            listIpoteca();

        }
    }//GEN-LAST:event_btnAdaugareActionPerformed

    public void clean_field() {
        txtNrCont.setText("");
        txtCodFiliala.setText("");
        txtSumaImprumutata.setText("");
        txtSumaRestituit.setText("");
        txtTipCont.setText("");
        txtTipIpoteca.setText("");
        txtRataDobanzii.setText("");
        txtNrClient.setText("");
    }

    private void btnEditareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditareActionPerformed
        // TODO add your handling code here:

        if (txtNrCont.getText().isEmpty() || txtCodFiliala.getText().isEmpty() || txtSumaImprumutata.getText().isEmpty()
                || txtSumaRestituit.getText().isEmpty() || txtTipCont.getText().isEmpty() || txtRataDobanzii.getText().isEmpty()
                || txtNrClient.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "completati toate campurile!");
        } else {
            Ipoteca ipt = new Ipoteca();
            ipt.setNumar_cont(txtNrCont.getText());
            ipt.setCod_filiala_conducere(Integer.parseInt(txtCodFiliala.getText()));
            ipt.setSuma_imprumutata(Float.parseFloat(txtSumaImprumutata.getText()));
            ipt.setSuma_de_restituit(Float.parseFloat(txtSumaRestituit.getText()));
            ipt.setTip_cont(txtTipCont.getText());
            ipt.setTip_ipoteca(txtTipIpoteca.getText());
            ipt.setRata_dobanzii(Float.parseFloat(txtRataDobanzii.getText()));
            ipt.setNr_client(Integer.parseInt(txtNrClient.getText()));
            String mesaj = ibo.editIpoteca(ipt);
            JOptionPane.showMessageDialog(null, mesaj);
            clean_field();
            listIpoteca();

        }

    }//GEN-LAST:event_btnEditareActionPerformed

    private void btnStergereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStergereActionPerformed
        // TODO add your handling code here:

        if (txtNrCont.getText().isEmpty() || txtCodFiliala.getText().isEmpty() || txtSumaImprumutata.getText().isEmpty()
                || txtSumaRestituit.getText().isEmpty() || txtTipCont.getText().isEmpty() || txtRataDobanzii.getText().isEmpty()
                || txtNrClient.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "completati toate campurile!");
        } else {
            String mesaj = ibo.deleteIpoteca(txtNrCont.getText());
            JOptionPane.showMessageDialog(null, mesaj);
            clean_field();
            listIpoteca();

        }

    }//GEN-LAST:event_btnStergereActionPerformed

    private void btnResetareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetareActionPerformed
        // TODO add your handling code here:
        clean_field();

    }//GEN-LAST:event_btnResetareActionPerformed

    private void btnListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaActionPerformed
        // TODO add your handling code here:
       JFrame lista = new ListaDobanzi();
        lista.setTitle("Lista dobanzilor pentru fiecare client: ");
        lista.setSize(500, 300);
        lista.setLocationRelativeTo(null);
        lista.setVisible(true);
        lista.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnListaActionPerformed

    private void tbIpotecaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbIpotecaMouseClicked
        // TODO add your handling code here:

        int selection = tbIpoteca.rowAtPoint(evt.getPoint());
        txtNrCont.setText(tbIpoteca.getValueAt(selection, 0) + "");
        txtCodFiliala.setText(tbIpoteca.getValueAt(selection, 1) + "");
        txtSumaImprumutata.setText(tbIpoteca.getValueAt(selection, 2) + "");
        txtSumaRestituit.setText(tbIpoteca.getValueAt(selection, 3) + "");
        txtTipCont.setText(tbIpoteca.getValueAt(selection, 4) + "");
        txtTipIpoteca.setText(tbIpoteca.getValueAt(selection, 5) + "");
        txtRataDobanzii.setText(tbIpoteca.getValueAt(selection, 6) + "");
        txtNrClient.setText(tbIpoteca.getValueAt(selection, 7) + "");

    }//GEN-LAST:event_tbIpotecaMouseClicked

    private void btnInapoi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInapoi1ActionPerformed
        // TODO add your handling code here:
          Menu menu = new Menu();
        this.dispose();
        menu.setVisible(true);
    }//GEN-LAST:event_btnInapoi1ActionPerformed

    private void btnSumaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaCActionPerformed
        // TODO add your handling code here:
        JFrame frCredite = new SumaCredite();
        frCredite.setTitle("Suma creditelor pentru fiecare filiala: ");
        frCredite.setSize(500, 300);
        frCredite.setLocationRelativeTo(null);
        frCredite.setVisible(true);
        frCredite.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnSumaCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameIpoteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameIpoteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameIpoteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameIpoteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameIpoteca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdaugare;
    private javax.swing.JButton btnEditare;
    private javax.swing.JButton btnInapoi1;
    private javax.swing.JButton btnLista;
    private javax.swing.JButton btnResetare;
    private javax.swing.JButton btnStergere;
    private javax.swing.JButton btnSumaC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbIpoteca;
    private javax.swing.JTextField txtCodFiliala;
    private javax.swing.JTextField txtNrClient;
    private javax.swing.JTextField txtNrCont;
    private javax.swing.JTextField txtRataDobanzii;
    private javax.swing.JTextField txtSumaImprumutata;
    private javax.swing.JTextField txtSumaRestituit;
    private javax.swing.JTextField txtTipCont;
    private javax.swing.JTextField txtTipIpoteca;
    // End of variables declaration//GEN-END:variables
}
