/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bo.ClientBO;
import entity.Client;
import javax.swing.JOptionPane;

/**
 *
 * @author Andrei Buculea
 */
public class frameClient extends javax.swing.JFrame {

    /**
     * Creates new form frameClient
     */
    
    private ClientBO cbo= new ClientBO();
    
    public frameClient() {
        initComponents();
         listClient();
         setTitle("Clienti");
    }
    
    public void listClient(){
        cbo.listClient(tbClient);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNumeClient = new javax.swing.JTextField();
        txtNrclient = new javax.swing.JTextField();
        txtAdresaClient = new javax.swing.JTextField();
        btnInapoi = new javax.swing.JButton();
        btnAdaugare1 = new javax.swing.JButton();
        btnEditare = new javax.swing.JButton();
        btnStergere = new javax.swing.JButton();
        btnResetare = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbClient = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Clienti");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 10, 1800, -1));

        jLabel2.setText("Nr client");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel3.setText("Nume client");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel4.setText("Adresa client");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));
        jPanel1.add(txtNumeClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 450, 30));
        jPanel1.add(txtNrclient, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 450, 30));
        jPanel1.add(txtAdresaClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 450, 30));

        btnInapoi.setText("Inapoi");
        btnInapoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInapoiActionPerformed(evt);
            }
        });
        jPanel1.add(btnInapoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 580, 230, 110));

        btnAdaugare1.setText("Adaugare");
        btnAdaugare1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdaugare1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdaugare1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 580, 240, 110));

        btnEditare.setText("Editare");
        btnEditare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditareActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditare, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 580, 210, 110));

        btnStergere.setText("Stergere");
        btnStergere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStergereActionPerformed(evt);
            }
        });
        jPanel1.add(btnStergere, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 580, 210, 110));

        btnResetare.setText("Resetare");
        btnResetare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetareActionPerformed(evt);
            }
        });
        jPanel1.add(btnResetare, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 580, 220, 110));

        tbClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbClientMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbClient);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, 1160, 480));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1810, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdaugare1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdaugare1ActionPerformed
        // TODO add your handling code here:
        if(txtNrclient.getText().isEmpty() || txtAdresaClient.getText().isEmpty() || txtNumeClient.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "completati toate campurile!");
        }else{
            Client cli=new Client();
            cli.setNr_client(Integer.parseInt(txtNrclient.getText()));
            cli.setAdresa_client(txtAdresaClient.getText());
            cli.setNume_client(txtNumeClient.getText());
            String mesaj = cbo.addClient(cli);
            JOptionPane.showMessageDialog(null, mesaj);
              clean_field();
            listClient();
          
        }
    }//GEN-LAST:event_btnAdaugare1ActionPerformed

     public void clean_field(){
        txtNrclient.setText("");
        txtAdresaClient.setText("");
        txtNumeClient.setText("");
    }
     
    private void btnEditareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditareActionPerformed
        // TODO add your handling code here:
        
         if(txtNrclient.getText().isEmpty() || txtAdresaClient.getText().isEmpty() || txtNumeClient.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "completati toate campurile!");
        }else{
            Client cli=new Client();
            cli.setNr_client(Integer.parseInt(txtNrclient.getText()));
            cli.setAdresa_client(txtAdresaClient.getText());
            cli.setNume_client(txtNumeClient.getText());
            String mesaj = cbo.editClient(cli);
            JOptionPane.showMessageDialog(null, mesaj);
              clean_field();
            listClient();
          
        }
        
    }//GEN-LAST:event_btnEditareActionPerformed

    private void btnStergereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStergereActionPerformed
        // TODO add your handling code here:
        
          if(txtNrclient.getText().isEmpty() || txtAdresaClient.getText().isEmpty() || txtNumeClient.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "completati toate campurile!");
        }else{
            
            String mesaj = cbo.deleteClient(Integer.parseInt(txtNrclient.getText()));
            JOptionPane.showMessageDialog(null, mesaj);
              clean_field();
            listClient();
          
        }
        
    }//GEN-LAST:event_btnStergereActionPerformed

    private void btnResetareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetareActionPerformed
        // TODO add your handling code here:
        txtNrclient.setText("");
        txtAdresaClient.setText("");
        txtNumeClient.setText("");
    }//GEN-LAST:event_btnResetareActionPerformed

    private void btnInapoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInapoiActionPerformed
        // TODO add your handling code here:
        
         this.dispose();
           Menu menu=new Menu();
           menu.setVisible(true);
        
    }//GEN-LAST:event_btnInapoiActionPerformed

    private void tbClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbClientMouseClicked
        // TODO add your handling code here:
        
         int selection =  tbClient.rowAtPoint(evt.getPoint());
       txtNrclient.setText(tbClient.getValueAt(selection, 0)+"");
        txtAdresaClient.setText(tbClient.getValueAt(selection, 1)+"");
        txtNumeClient.setText(tbClient.getValueAt(selection, 2)+"");
        
    }//GEN-LAST:event_tbClientMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdaugare1;
    private javax.swing.JButton btnEditare;
    private javax.swing.JButton btnInapoi;
    private javax.swing.JButton btnResetare;
    private javax.swing.JButton btnStergere;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbClient;
    private javax.swing.JTextField txtAdresaClient;
    private javax.swing.JTextField txtNrclient;
    private javax.swing.JTextField txtNumeClient;
    // End of variables declaration//GEN-END:variables
}
